function SitKusa = importcsv_EE(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SITKUSA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  SITKUSA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SitKusa = importfile("C:\Users\Yoram\OneDrive - University of Idaho\Desktop\PhD pos\SURGE_CYCLES\peclet_nb\csv_earth_engine\SitKusa.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Aug-2022 09:10:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["systemindex", "bed_elev", "bed_slope", "datetime", "ice_thickness", "lat", "lon", "offset", "surf_elev", "timestamp", "geo"];
opts.VariableTypes = ["string", "double", "double", "datetime", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["systemindex", "geo"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["systemindex", "geo"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
SitKusa = readtable(filename, opts);

end