function Turnerstats = importcsv_python(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TURNERSTATS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TURNERSTATS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Turnerstats = importfile("C:\Users\Yoram\OneDrive - University of Idaho\Desktop\PhD pos\SURGE_CYCLES\peclet_nb\csv_python\Turner_stats.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Sep-2022 22:06:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["elevation", "slope", "elevation_bed", "slope_bed", "systemindex", "offset", "lat", "lon"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "systemindex", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "systemindex", "EmptyFieldRule", "auto");

% Import the data
Turnerstats = readtable(filename, opts);

end